import type { AppLocale } from "@/i18n/routing";

export const publicationTypes = ["technical-article", "research-summary", "project-write-up", "case-study"] as const;
export type PublicationType = (typeof publicationTypes)[number];

type Reference = { label: string; organization: string; href: string };
type LocalizedPublication = {
  title: string; summary: string; context: string; method: string[]; evidence: string[];
  findings: string[]; limitations: string[]; implications: string[]; references: Reference[];
};
export type Publication = {
  slug: string; type: PublicationType; author: string; published: string; reviewed: string; updated: string;
  relatedServices: string[]; relatedTopics: string[]; sanitized: boolean;
  content: Record<AppLocale, LocalizedPublication>;
};

const owaspAsvs = { label: "OWASP Application Security Verification Standard", organization: "OWASP Foundation", href: "https://owasp.org/www-project-application-security-verification-standard/" };
const nistIr = { label: "Incident Response Recommendations and Considerations — NIST SP 800-61 Rev. 3", organization: "NIST", href: "https://csrc.nist.gov/pubs/sp/800/61/r3/final" };

export const publications: Publication[] = [
  {
    slug: "authorization-checks-in-small-web-apps", type: "technical-article", author: "Nikita Wokurka", published: "2026-07-12", reviewed: "2026-07-12", updated: "2026-07-12", relatedServices: ["web-application-security-review"], relatedTopics: ["web-app-security", "secure-development"], sanitized: true,
    content: {
      en: { title: "Authorization checks in small web applications", summary: "A technical article showing why authentication does not replace record-level authorization.", context: "Small applications often protect routes with login checks while leaving object ownership implicit.", method: ["Model the request and trust boundaries", "Identify the server-side ownership decision", "Compare the implementation with an explicit access rule"], evidence: ["A fictional invoice endpoint is used as a safe example", "The control model is compared with OWASP ASVS requirements"], findings: ["A valid session identifies a user but does not authorize every record", "Ownership rules must be enforced at the data access boundary"], limitations: ["The fixture is illustrative and is not evidence about a real client system"], implications: ["Write access rules before implementation", "Test authorization with multiple identities and object owners"], references: [owaspAsvs] },
      de: { title: "Berechtigungsprüfungen in kleinen Webanwendungen", summary: "Technischer Artikel darüber, warum Authentifizierung keine objektbezogene Autorisierung ersetzt.", context: "Kleine Anwendungen schützen Routen oft durch Login-Prüfungen, lassen den Besitz einzelner Datensätze aber implizit.", method: ["Request und Trust Boundaries modellieren", "Serverseitige Besitzentscheidung benennen", "Implementierung mit einer expliziten Zugriffsregel vergleichen"], evidence: ["Ein fiktiver Rechnungs-Endpunkt dient als sicheres Beispiel", "Das Kontrollmodell wird mit OWASP-ASVS-Anforderungen verglichen"], findings: ["Eine gültige Session identifiziert einen Nutzer, autorisiert aber nicht jeden Datensatz", "Besitzregeln müssen an der Datenzugriffsgrenze durchgesetzt werden"], limitations: ["Das Beispiel ist rein illustrativ und kein Nachweis über ein reales Kundensystem"], implications: ["Zugriffsregeln vor der Implementierung formulieren", "Autorisierung mit mehreren Identitäten und Besitzern testen"], references: [owaspAsvs] },
    },
  },
  {
    slug: "incident-triage-evidence-review", type: "research-summary", author: "Nikita Wokurka", published: "2026-07-12", reviewed: "2026-07-12", updated: "2026-07-12", relatedServices: ["incident-response-guidance"], relatedTopics: ["incident-response"], sanitized: true,
    content: {
      en: { title: "Research summary: first decisions in incident triage", summary: "A source-backed summary of preparation, evidence preservation, containment, and escalation during early incident triage.", context: "Early decisions are made with incomplete information and can affect evidence and recovery.", method: ["Review current NIST incident-response guidance", "Separate preparation, detection, response, and recovery decisions"], evidence: ["Primary guidance from NIST SP 800-61 Rev. 3"], findings: ["Roles and escalation paths reduce avoidable delay", "Containment must balance operational impact and evidence preservation"], limitations: ["General guidance cannot replace incident-specific legal, forensic, or operational expertise"], implications: ["Prepare contacts and decision authority before an incident", "Record actions, reasons, and uncertainty"], references: [nistIr] },
      de: { title: "Research Summary: erste Entscheidungen bei der Incident-Triage", summary: "Quellengestützte Zusammenfassung zu Vorbereitung, Beweissicherung, Eindämmung und Eskalation in der frühen Incident-Triage.", context: "Frühe Entscheidungen entstehen mit unvollständigen Informationen und können Beweise und Wiederherstellung beeinflussen.", method: ["Aktuelle NIST-Empfehlungen zur Incident Response prüfen", "Entscheidungen zu Vorbereitung, Erkennung, Reaktion und Recovery trennen"], evidence: ["Primärquelle NIST SP 800-61 Rev. 3"], findings: ["Rollen und Eskalationswege reduzieren vermeidbare Verzögerungen", "Eindämmung muss Betriebsfolgen und Beweissicherung abwägen"], limitations: ["Allgemeine Leitlinien ersetzen keine vorfallspezifische rechtliche, forensische oder operative Expertise"], implications: ["Kontakte und Entscheidungsbefugnisse vor einem Vorfall vorbereiten", "Maßnahmen, Gründe und Unsicherheiten dokumentieren"], references: [nistIr] },
    },
  },
  {
    slug: "niwo-metadata-system", type: "project-write-up", author: "Nikita Wokurka", published: "2026-07-12", reviewed: "2026-07-12", updated: "2026-07-12", relatedServices: ["web-application-security-review"], relatedTopics: ["secure-development"], sanitized: true,
    content: {
      en: { title: "Project write-up: NIWO’s route-aware metadata system", summary: "How this public website keeps localized routes, metadata, sitemap entries, and validation aligned.", context: "Metadata was distributed across layouts, translations, routes, and smoke tests.", method: ["Inventory public routes", "Centralize route relationships", "Validate generated HTML rather than source values alone"], evidence: ["The implementation is available in the public niwo-webapp repository"], findings: ["A shared route model reduces sitemap and test drift", "Generated-output checks catch framework integration errors"], limitations: ["Production CDN and crawler behavior still require external verification"], implications: ["Treat discoverability metadata as tested application behavior"], references: [{ label: "niwo-webapp source repository", organization: "NIWO", href: "https://github.com/n1wo/niwo-webapp" }] },
      de: { title: "Projektbericht: NIWOs routenbezogenes Metadatensystem", summary: "Wie diese öffentliche Website lokalisierte Routen, Metadaten, Sitemap-Einträge und Validierung konsistent hält.", context: "Metadaten waren über Layouts, Übersetzungen, Routen und Smoke-Tests verteilt.", method: ["Öffentliche Routen inventarisieren", "Routenbeziehungen zentralisieren", "Generiertes HTML statt nur Quellwerte prüfen"], evidence: ["Die Implementierung ist im öffentlichen niwo-webapp-Repository einsehbar"], findings: ["Ein gemeinsames Routenmodell reduziert Sitemap- und Test-Drift", "Prüfungen der Ausgabe erkennen Integrationsfehler des Frameworks"], limitations: ["Produktions-CDN und Crawler-Verhalten brauchen weiterhin externe Verifikation"], implications: ["Discoverability-Metadaten als getestetes Anwendungsverhalten behandeln"], references: [{ label: "niwo-webapp Quellrepository", organization: "NIWO", href: "https://github.com/n1wo/niwo-webapp" }] },
    },
  },
  {
    slug: "fictional-saas-access-review", type: "case-study", author: "Nikita Wokurka", published: "2026-07-12", reviewed: "2026-07-12", updated: "2026-07-12", relatedServices: ["web-application-security-review"], relatedTopics: ["web-app-security", "penetration-testing"], sanitized: true,
    content: {
      en: { title: "Sanitized case-study template: fictional SaaS access review", summary: "A clearly fictional fixture demonstrating how an anonymized case study records authorization, scope, evidence, findings, and limitations.", context: "Fictional company Example SaaS Ltd. authorizes a review of a staging invoice workflow. No real client, system, result, or engagement data is used.", method: ["Record written authorization and staging-only scope", "Review selected request flows and access rules", "Validate a fictional finding with two test identities"], evidence: ["Sanitized request/response fixture with invented identifiers", "Fictional access-control matrix"], findings: ["Fixture finding: one endpoint lacks an object-ownership check", "Fixture deliverable: a scoped finding and retest condition"], limitations: ["Entirely fictional; it makes no claim about NIWO clients or outcomes", "Does not represent a full penetration test"], implications: ["Case studies must label anonymization and distinguish evidence from interpretation"], references: [owaspAsvs] },
      de: { title: "Bereinigte Case-Study-Vorlage: fiktives SaaS-Zugriffsreview", summary: "Klar fiktives Beispiel dafür, wie eine anonymisierte Case Study Autorisierung, Scope, Nachweise, Befunde und Grenzen dokumentiert.", context: "Das fiktive Unternehmen Example SaaS Ltd. autorisiert eine Prüfung eines Staging-Rechnungsablaufs. Es werden keine realen Kunden-, System-, Ergebnis- oder Auftragsdaten genutzt.", method: ["Schriftliche Autorisierung und reinen Staging-Scope dokumentieren", "Ausgewählte Request-Flows und Zugriffsregeln prüfen", "Fiktiven Befund mit zwei Testidentitäten validieren"], evidence: ["Bereinigtes Request-/Response-Beispiel mit erfundenen Kennungen", "Fiktive Zugriffskontrollmatrix"], findings: ["Beispielbefund: Ein Endpunkt prüft den Objektbesitz nicht", "Beispielergebnis: abgegrenzter Befund und Retest-Bedingung"], limitations: ["Vollständig fiktiv; keine Aussage über NIWO-Kunden oder Ergebnisse", "Stellt keinen vollständigen Penetrationstest dar"], implications: ["Case Studies müssen Anonymisierung kennzeichnen und Nachweise von Interpretation trennen"], references: [owaspAsvs] },
    },
  },
];

export function getPublication(slug: string) { return publications.find((item) => item.slug === slug); }

