import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { publications } from "@/data/publications";
import { buildMetadata } from "@/i18n/metadata";
import { Link } from "@/i18n/navigation";

const copy = { en: { title: "Evidence and technical writing", description: "Source-backed technical articles, research summaries, project write-ups, and clearly sanitized case-study templates from NIWO.", intro: "These publications make methods, evidence, limitations, and practical implications visible. Fixtures are clearly marked and never imply real clients or outcomes." }, de: { title: "Nachweise und technische Beiträge", description: "Quellengestützte technische Artikel, Research Summaries, Projektberichte und klar bereinigte Case-Study-Vorlagen von NIWO.", intro: "Diese Beiträge machen Methode, Nachweise, Grenzen und praktische Bedeutung sichtbar. Beispiele sind klar gekennzeichnet und behaupten keine realen Kunden oder Ergebnisse." } } as const;
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; const c = copy[locale === "de" ? "de" : "en"]; return buildMetadata({ locale, title: `${c.title} | niwo`, description: c.description, path: "/insights", socialImageAlt: c.title }); }
export default async function InsightsPage({ params }: { params: Promise<{ locale: string }> }) { if (publications.length === 0) notFound(); const { locale } = await params; const lang = locale === "de" ? "de" : "en"; const c = copy[lang]; return <section className="bg-[var(--background)] px-6 pb-28 pt-32 sm:px-10 lg:px-16"><div className="mx-auto max-w-6xl"><header className="border-b border-white/[0.08] pb-14"><h1 className="font-mono text-4xl font-bold text-white sm:text-5xl">{c.title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-zinc-300">{c.intro}</p></header><div className="divide-y divide-white/[0.08]">{publications.map((item) => { const p = item.content[lang]; return <article key={item.slug} className="py-9"><p className="font-mono text-xs uppercase tracking-[0.22em] text-[var(--color-accent-light)]">{item.type.replaceAll("-", " ")}</p><h2 className="mt-3 font-mono text-2xl font-semibold text-white">{p.title}</h2><p className="mt-4 max-w-3xl leading-7 text-zinc-400">{p.summary}</p><Link href={`/insights/${item.slug}`} className="mt-5 inline-flex font-mono text-sm text-[var(--color-accent-light)] hover:text-white">{lang === "de" ? "Beitrag lesen" : "Read publication"} &rarr;</Link></article>; })}</div></div></section>; }

