import type { LabEmail } from './copy';

type Localized = [en: string, de: string];

interface ScenarioSeed {
  category: Localized;
  channel?: 'email' | 'sms' | 'qr';
  difficulty: Localized;
  time: Localized;
  fromName: Localized;
  fromAddr: string;
  subject: Localized;
  preview: Localized;
  isPhishing: boolean;
  damage: number;
  lossType: Localized;
  body: [Localized, Localized, Localized?];
  cta?: { text: Localized; url: string };
  explain: Localized;
  clues: [Localized, Localized, Localized, Localized];
}

const seeds: ScenarioSeed[] = [
  {
    category: ['Shared document', 'Geteiltes Dokument'], difficulty: ['Medium', 'Mittel'], time: ['8:06 AM', '8:06 Uhr'],
    fromName: ['Google Drive', 'Google Drive'], fromAddr: 'drive-share@google-docs-review.com',
    subject: ['Shared: Q3 hiring plan', 'Freigegeben: Einstellungsplan Q3'], preview: ['Nina shared a document with you...', 'Nina hat ein Dokument mit dir geteilt...'],
    isPhishing: true, damage: 7800, lossType: ['work account stolen through a fake Google sign-in', 'Arbeitskonto über eine gefälschte Google-Anmeldung gestohlen'],
    body: [['Nina shared a document with you: Q3 hiring plan.', 'Nina hat ein Dokument mit dir geteilt: Einstellungsplan Q3.'], ['You need to sign in again before the link expires this afternoon.', 'Du musst dich erneut anmelden, bevor der Link heute Nachmittag abläuft.']],
    cta: { text: ['Open shared document', 'Geteiltes Dokument öffnen'], url: 'http://google-docs-review.com/share/q3-plan' },
    explain: ['This imitates a normal file share, but the sender and link are not Google. The short expiry creates pressure to enter credentials.', 'Das imitiert eine normale Dateifreigabe, aber Absender und Link gehören nicht zu Google. Die kurze Frist soll zur Eingabe von Zugangsdaten drängen.'],
    clues: [['Sender domain is google-docs-review.com, not google.com', 'Absenderdomain ist google-docs-review.com, nicht google.com'], ['Expiry pressure is used to rush the login', 'Ablaufdruck soll die Anmeldung beschleunigen'], ['The link leads to a fake sign-in page', 'Der Link führt zu einer gefälschten Anmeldung'], ['Unexpected document shares should be verified in Drive directly', 'Unerwartete Freigaben direkt in Drive prüfen']],
  },
  {
    category: ['Shared document', 'Geteiltes Dokument'], difficulty: ['Easy', 'Einfach'], time: ['9:31 AM', '9:31 Uhr'],
    fromName: ['Google Drive', 'Google Drive'], fromAddr: 'drive-shares-dm-noreply@google.com',
    subject: ['Shared with you: project notes', 'Für dich freigegeben: Projektnotizen'], preview: ['A file was shared from Google Drive...', 'Eine Datei wurde über Google Drive freigegeben...'],
    isPhishing: false, damage: 110, lossType: ['', ''],
    body: [['A file named "project notes" was shared with you in Google Drive.', 'Eine Datei namens "Projektnotizen" wurde in Google Drive mit dir geteilt.'], ['If you were expecting this, open Drive or use the button below.', 'Wenn du das erwartest, öffne Drive oder nutze den Button unten.']],
    cta: { text: ['Open in Drive', 'In Drive öffnen'], url: 'https://drive.google.com/drive/shared-with-me' },
    explain: ['This is a normal Google Drive notification. The sender and destination are real Google domains, and there is no threat or password demand.', 'Das ist eine normale Google-Drive-Benachrichtigung. Absender und Ziel sind echte Google-Domains, ohne Drohung oder Passwortforderung.'],
    clues: [['Sender is a google.com notification address', 'Absender ist eine google.com-Benachrichtigungsadresse'], ['The link goes to drive.google.com', 'Der Link führt zu drive.google.com'], ['No countdown or account threat', 'Kein Countdown und keine Kontodrohung'], ['You can verify it by opening Drive directly', 'Du kannst es direkt in Drive prüfen']],
  },
  {
    category: ['OAuth app', 'OAuth-App'], difficulty: ['Hard', 'Schwer'], time: ['10:12 AM', '10:12 Uhr'],
    fromName: ['Notion Workspace', 'Notion Workspace'], fromAddr: 'workspace@notion-integrations.app',
    subject: ['Approve the new Notion calendar sync', 'Neue Notion-Kalendersynchronisierung freigeben'], preview: ['Admin approval needed for calendar access...', 'Admin-Freigabe für Kalenderzugriff nötig...'],
    isPhishing: true, damage: 16000, lossType: ['mailbox and calendar access granted to a rogue OAuth app', 'Postfach- und Kalenderzugriff an eine fremde OAuth-App vergeben'],
    body: [['Your workspace is moving to the new calendar sync.', 'Euer Workspace wechselt zur neuen Kalendersynchronisierung.'], ['Approve the app today so meetings keep syncing.', 'Gib die App heute frei, damit Meetings weiter synchronisiert werden.']],
    cta: { text: ['Approve app access', 'App-Zugriff freigeben'], url: 'http://notion-calendar-approve.app/oauth' },
    explain: ['OAuth consent phishing asks for access instead of a password. The fake domain and broad calendar/mail access request are the danger.', 'OAuth-Phishing fragt nach Zugriff statt nach einem Passwort. Die falsche Domain und breite Kalender-/Mailrechte sind das Risiko.'],
    clues: [['Notion does not use notion-integrations.app for approval mail', 'Notion nutzt nicht notion-integrations.app für Freigaben'], ['OAuth approval can expose data without stealing a password', 'OAuth-Freigaben können Daten preisgeben, ohne ein Passwort zu stehlen'], ['Urgency is tied to business continuity', 'Dringlichkeit wird mit Arbeitsfähigkeit begründet'], ['Admin consent should be checked in the real admin console', 'Admin-Freigaben im echten Admin-Portal prüfen']],
  },
  {
    category: ['Invoice', 'Rechnung'], difficulty: ['Hard', 'Schwer'], time: ['11:48 AM', '11:48 Uhr'],
    fromName: ['Keller Print GmbH', 'Keller Print GmbH'], fromAddr: 'billing@keller-prlnt.de',
    subject: ['RE: June print invoice - corrected IBAN', 'AW: Druckrechnung Juni - korrigierte IBAN'], preview: ['Please use the corrected bank details...', 'Bitte die korrigierte Bankverbindung nutzen...'],
    isPhishing: true, damage: 38000, lossType: ['vendor payment redirected to a look-alike supplier domain', 'Lieferantenzahlung an eine Look-alike-Domain umgeleitet'],
    body: [['Hi, sorry for the confusion on the June invoice.', 'Hallo, entschuldige bitte die Verwirrung bei der Juni-Rechnung.'], ['Our bank merged branches, so please use the corrected IBAN attached below for this payment.', 'Unsere Bank hat Filialen zusammengelegt, bitte nutze für diese Zahlung die unten korrigierte IBAN.'], ['Can you confirm once the transfer is released?', 'Kannst du kurz bestätigen, sobald die Überweisung raus ist?']],
    explain: ['This is a BEC-style invoice change. The domain swaps an "i" for an "l" in print, and bank changes must be verified by a known phone number.', 'Das ist BEC-Rechnungsbetrug. Die Domain ersetzt ein "i" durch ein "l"; Bankänderungen müssen über eine bekannte Nummer bestätigt werden.'],
    clues: [['Look-alike domain: keller-prlnt.de', 'Look-alike-Domain: keller-prlnt.de'], ['Bank detail changes are high-risk', 'Bankdatenänderungen sind Hochrisiko'], ['The request arrives inside a plausible invoice thread', 'Die Anfrage wirkt wie Teil eines echten Rechnungsverlaufs'], ['Payment changes need second-channel verification', 'Zahlungsänderungen brauchen eine zweite Bestätigung']],
  },
  {
    category: ['Procurement', 'Einkauf'], difficulty: ['Medium', 'Mittel'], time: ['1:04 PM', '13:04 Uhr'],
    fromName: ['Procurement Portal', 'Einkaufsportal'], fromAddr: 'no-reply@vendors.northwind-tools.com',
    subject: ['Supplier profile review due Friday', 'Lieferantenprofil bis Freitag prüfen'], preview: ['Please review your supplier contacts...', 'Bitte Lieferantenkontakte prüfen...'],
    isPhishing: false, damage: 130, lossType: ['', ''],
    body: [['Quarterly supplier contact review is open.', 'Die quartalsweise Prüfung der Lieferantenkontakte ist geöffnet.'], ['Use the vendor portal or your bookmark to confirm owner, phone, and escalation details by Friday.', 'Nutze das Lieferantenportal oder dein Lesezeichen, um Owner, Telefon und Eskalationsdaten bis Freitag zu bestätigen.']],
    cta: { text: ['Open vendor portal', 'Lieferantenportal öffnen'], url: 'https://vendors.northwind-tools.com/reviews' },
    explain: ['This is a legitimate process mail. It asks for review in the normal portal and does not request payment changes by email.', 'Das ist eine legitime Prozessmail. Sie verweist auf das normale Portal und fordert keine Zahlungsänderung per E-Mail.'],
    clues: [['Internal vendor domain matches the company', 'Interne Vendor-Domain passt zum Unternehmen'], ['No new bank details are included', 'Es werden keine neuen Bankdaten mitgeschickt'], ['Asks for portal review, not reply-by-email', 'Fordert Portalprüfung statt Antwort per Mail'], ['Specific but low-pressure deadline', 'Konkrete, aber nicht panische Frist']],
  },
  {
    channel: 'sms',
    category: ['SMS', 'SMS'], difficulty: ['Easy', 'Einfach'], time: ['2:20 PM', '14:20 Uhr'],
    fromName: ['SMS: Packstation', 'SMS: Packstation'], fromAddr: '+49 171 000 4421',
    subject: ['SMS: delivery address incomplete', 'SMS: Lieferadresse unvollständig'], preview: ['Update address: dhl-paket24.info...', 'Adresse aktualisieren: dhl-paket24.info...'],
    isPhishing: true, damage: 690, lossType: ['card and address data stolen through a smishing page', 'Karten- und Adressdaten über eine Smishing-Seite gestohlen'],
    body: [['DHL: Your parcel cannot be delivered because the address is incomplete.', 'DHL: Ihr Paket kann wegen unvollständiger Adresse nicht zugestellt werden.'], ['Update within 6 hours to avoid return.', 'Aktualisieren Sie die Daten innerhalb von 6 Stunden, sonst geht die Sendung zurück.']],
    cta: { text: ['Update delivery address', 'Lieferadresse aktualisieren'], url: 'http://dhl-paket24.info/address' },
    explain: ['Smishing often uses delivery pressure and short mobile links. The domain is not DHL and the six-hour deadline is pure pressure.', 'Smishing nutzt oft Paketdruck und kurze Mobil-Links. Die Domain gehört nicht zu DHL und die Sechs-Stunden-Frist ist Druck.'],
    clues: [['SMS sender is just a phone number', 'SMS-Absender ist nur eine Telefonnummer'], ['Fake DHL-like domain', 'Gefälschte DHL-ähnliche Domain'], ['Short deadline pushes mobile clicking', 'Kurze Frist drängt zum mobilen Klick'], ['Real delivery issues can be checked in the official app', 'Echte Zustellprobleme in der offiziellen App prüfen']],
  },
  {
    category: ['Callback', 'Rückruf'], difficulty: ['Medium', 'Mittel'], time: ['3:42 PM', '15:42 Uhr'],
    fromName: ['PayPal Billing', 'PayPal Abrechnung'], fromAddr: 'billing@paypal-casecenter.net',
    subject: ['Invoice created for EUR 489.00', 'Rechnung über 489,00 EUR erstellt'], preview: ['If this was not you, call support...', 'Wenn Sie das nicht waren, rufen Sie den Support an...'],
    isPhishing: true, damage: 4200, lossType: ['remote-support scam after calling the number in the email', 'Remote-Support-Betrug nach Anruf der Nummer in der E-Mail'],
    body: [['A PayPal invoice for EUR 489.00 has been created.', 'Eine PayPal-Rechnung über 489,00 EUR wurde erstellt.'], ['If this was not you, call our cancellation desk immediately: +49 30 700 140 92.', 'Wenn Sie das nicht waren, rufen Sie sofort unsere Storno-Hotline an: +49 30 700 140 92.']],
    explain: ['The phone number is the payload. Callback fraud tries to make you call a fake support desk that walks you into remote access or payment.', 'Die Telefonnummer ist der Köder. Rückrufbetrug bringt dich zu einem falschen Support, der Fernzugriff oder Zahlung erzwingen will.'],
    clues: [['Domain is not paypal.com', 'Domain ist nicht paypal.com'], ['The main action is a phone call, not a link', 'Die Hauptaktion ist ein Anruf, kein Link'], ['Large fake invoice creates panic', 'Hohe Fake-Rechnung erzeugt Panik'], ['Use known support channels, never numbers from the alert', 'Nur bekannte Supportkanäle nutzen, nie Nummern aus der Warnung']],
  },
  {
    category: ['Voicemail', 'Mailbox'], difficulty: ['Medium', 'Mittel'], time: ['4:11 PM', '16:11 Uhr'],
    fromName: ['Teams Voicemail', 'Teams Voicemail'], fromAddr: 'voicemail@teams-messagehub.com',
    subject: ['New voicemail from +49 228 444 019', 'Neue Sprachnachricht von +49 228 444 019'], preview: ['Listen to the voicemail message...', 'Sprachnachricht anhören...'],
    isPhishing: true, damage: 9500, lossType: ['malicious attachment opened from a fake voicemail notification', 'schädlicher Anhang aus falscher Voicemail-Benachrichtigung geöffnet'],
    body: [['You missed a call and received a voicemail.', 'Du hast einen Anruf verpasst und eine Sprachnachricht erhalten.'], ['Open the secure message file to listen.', 'Öffne die sichere Nachrichtendatei, um sie anzuhören.']],
    cta: { text: ['Listen to voicemail.html', 'Voicemail.html anhören'], url: 'http://teams-messagehub.com/voicemail.html' },
    explain: ['Fake voicemail lures often hide the attack in an HTML attachment or link. The sender is not Microsoft Teams.', 'Falsche Voicemail-Köder verstecken den Angriff oft in HTML-Anhängen oder Links. Der Absender ist nicht Microsoft Teams.'],
    clues: [['Teams notifications should come from Microsoft domains', 'Teams-Benachrichtigungen sollten von Microsoft-Domains kommen'], ['HTML voicemail files are suspicious', 'HTML-Voicemail-Dateien sind verdächtig'], ['Unknown phone number adds curiosity pressure', 'Unbekannte Nummer erzeugt Neugierdruck'], ['Open voicemail from Teams directly', 'Sprachnachrichten direkt in Teams öffnen']],
  },
  {
    category: ['Password', 'Passwort'], difficulty: ['Easy', 'Einfach'], time: ['5:00 PM', '17:00 Uhr'],
    fromName: ['IT Security', 'IT-Sicherheit'], fromAddr: 'security@northwind-tools.com',
    subject: ['Password policy changes next week', 'Passwortrichtlinie ändert sich nächste Woche'], preview: ['No password reset is required today...', 'Heute ist kein Passwortwechsel nötig...'],
    isPhishing: false, damage: 100, lossType: ['', ''],
    body: [['Next week we will increase the minimum password length for new passwords.', 'Nächste Woche erhöhen wir die Mindestlänge für neue Passwörter.'], ['No reset is required today. When your password expires, use the normal account portal or company SSO page.', 'Heute ist kein Wechsel nötig. Wenn dein Passwort abläuft, nutze das normale Kontoportal oder die Firmen-SSO-Seite.']],
    explain: ['This is a safe awareness notice. It does not include a login link or threaten immediate lockout.', 'Das ist eine sichere Informationsmail. Sie enthält keinen Login-Link und droht keine sofortige Sperre an.'],
    clues: [['Internal security sender', 'Interner Sicherheitsabsender'], ['No link or password form', 'Kein Link und kein Passwortformular'], ['Tells users to use the normal portal', 'Verweist auf das normale Portal'], ['Calm timing and clear policy detail', 'Ruhiger Zeitplan und klare Richtlinie']],
  },
  {
    category: ['MFA', 'MFA'], difficulty: ['Hard', 'Schwer'], time: ['7:18 AM', '7:18 Uhr'],
    fromName: ['Okta Verify', 'Okta Verify'], fromAddr: 'alerts@okta-verify-support.com',
    subject: ['MFA fatigue protection: confirm your device', 'MFA-Schutz: Gerät bestätigen'], preview: ['Confirm your current device to stop prompts...', 'Aktuelles Gerät bestätigen, um Prompts zu stoppen...'],
    isPhishing: true, damage: 14000, lossType: ['MFA token captured by a fake identity provider page', 'MFA-Token über eine gefälschte Identity-Provider-Seite abgegriffen'],
    body: [['We detected repeated MFA prompts for your account.', 'Wir haben wiederholte MFA-Abfragen für dein Konto erkannt.'], ['Confirm your current device to stop unexpected notifications.', 'Bestätige dein aktuelles Gerät, um unerwartete Benachrichtigungen zu stoppen.']],
    cta: { text: ['Confirm trusted device', 'Vertrauenswürdiges Gerät bestätigen'], url: 'http://okta-verify-support.com/device' },
    explain: ['This abuses a real security idea: MFA fatigue. The domain is fake and the link would collect identity and approval data.', 'Das missbraucht ein echtes Sicherheitsthema: MFA-Fatigue. Die Domain ist falsch und der Link würde Identität und Freigaben abgreifen.'],
    clues: [['Fake Okta support domain', 'Gefälschte Okta-Support-Domain'], ['Security language is used as pressure', 'Sicherheitssprache wird als Druckmittel genutzt'], ['Asks you to fix MFA from an email link', 'MFA soll über E-Mail-Link repariert werden'], ['Use your SSO portal directly', 'SSO-Portal direkt öffnen']],
  },
  {
    category: ['HR', 'HR'], difficulty: ['Medium', 'Mittel'], time: ['9:03 AM', '9:03 Uhr'],
    fromName: ['Workday', 'Workday'], fromAddr: 'notifications@myworkday.com',
    subject: ['Time off request approved', 'Abwesenheitsantrag genehmigt'], preview: ['Your manager approved your request...', 'Deine Führungskraft hat den Antrag genehmigt...'],
    isPhishing: false, damage: 90, lossType: ['', ''],
    body: [['Your time off request has been approved.', 'Dein Abwesenheitsantrag wurde genehmigt.'], ['You can view the approval in Workday or ignore this email if you already saw it.', 'Du kannst die Genehmigung in Workday ansehen oder die Mail ignorieren, wenn du sie schon gesehen hast.']],
    cta: { text: ['Open Workday', 'Workday öffnen'], url: 'https://www.myworkday.com/' },
    explain: ['This is a normal HR notification from Workday. It is expected, low-pressure, and points to the real Workday domain.', 'Das ist eine normale HR-Benachrichtigung von Workday. Sie ist erwartbar, ohne Druck und verweist auf die echte Workday-Domain.'],
    clues: [['Sender and link are Workday domains', 'Absender und Link sind Workday-Domains'], ['No credentials requested in the email', 'Keine Zugangsdaten in der E-Mail verlangt'], ['No threat or secrecy', 'Keine Drohung oder Geheimhaltung'], ['Matches a normal HR workflow', 'Passt zu einem normalen HR-Ablauf']],
  },
  {
    category: ['Payroll', 'Gehaltsabrechnung'], difficulty: ['Hard', 'Schwer'], time: ['8:55 AM', '8:55 Uhr'],
    fromName: ['Payroll Services', 'Payroll Services'], fromAddr: 'payroll@northwind-payroll.co',
    subject: ['Confirm salary deposit account', 'Gehaltskonto bestätigen'], preview: ['Payroll migration requires confirmation...', 'Payroll-Migration erfordert Bestätigung...'],
    isPhishing: true, damage: 6200, lossType: ['salary payment redirected to an attacker-controlled account', 'Gehaltszahlung auf ein fremdes Konto umgeleitet'],
    body: [['We are migrating payroll records this month.', 'Wir migrieren diesen Monat Payroll-Daten.'], ['Confirm your salary deposit IBAN by 14:00 so payment is not delayed.', 'Bestätige deine IBAN bis 14:00 Uhr, damit die Auszahlung nicht verzögert wird.']],
    cta: { text: ['Confirm payroll account', 'Gehaltskonto bestätigen'], url: 'http://northwind-payroll.co/confirm' },
    explain: ['Payroll diversion is a business-process attack. The domain is external and the message asks for bank data under deadline pressure.', 'Payroll-Diversion ist ein Prozessangriff. Die Domain ist extern und fordert Bankdaten unter Zeitdruck.'],
    clues: [['External payroll look-alike domain', 'Externe Payroll-Look-alike-Domain'], ['Requests salary bank details', 'Fordert Gehaltsbankdaten'], ['Hard same-day deadline', 'Harte Frist am selben Tag'], ['Bank changes should use the HR portal directly', 'Bankänderungen direkt im HR-Portal durchführen']],
  },
  {
    channel: 'qr',
    category: ['QR code', 'QR-Code'], difficulty: ['Medium', 'Mittel'], time: ['12:07 PM', '12:07 Uhr'],
    fromName: ['Facilities Desk', 'Facility Desk'], fromAddr: 'facilities@northwind-tools.com',
    subject: ['New guest Wi-Fi QR poster', 'Neuer Gäste-WLAN-QR-Aushang'], preview: ['Please print for meeting rooms...', 'Bitte für Meetingräume ausdrucken...'],
    isPhishing: true, damage: 5200, lossType: ['credentials entered into a QR-hosted fake Wi-Fi portal', 'Zugangsdaten in einem per QR-Code verlinkten Fake-WLAN-Portal eingegeben'],
    body: [['Please print the attached QR poster for all meeting rooms.', 'Bitte den angehängten QR-Aushang für alle Meetingräume drucken.'], ['Visitors will scan it to accept the new Wi-Fi terms.', 'Besucher scannen ihn, um die neuen WLAN-Bedingungen zu akzeptieren.']],
    cta: { text: ['Preview QR destination', 'QR-Ziel anzeigen'], url: 'http://northwind-wifi-portal.com/guest' },
    explain: ['QR phishing bypasses hover habits. Even though the sender looks internal, the QR destination is an outside domain.', 'QR-Phishing umgeht Hover-Gewohnheiten. Obwohl der Absender intern wirkt, führt das QR-Ziel auf eine externe Domain.'],
    clues: [['QR destination is not a company domain', 'QR-Ziel ist keine Firmendomain'], ['Printing a malicious QR spreads the attack', 'Ein gedruckter schädlicher QR verbreitet den Angriff'], ['Wi-Fi portals should be managed by IT', 'WLAN-Portale gehören in die IT-Verwaltung'], ['Internal-looking sender is not enough', 'Intern wirkender Absender reicht nicht']],
  },
  {
    category: ['Calendar', 'Kalender'], difficulty: ['Easy', 'Einfach'], time: ['Mon 10:00', 'Mo 10:00'],
    fromName: ['Google Calendar', 'Google Kalender'], fromAddr: 'calendar-notification@google.com',
    subject: ['Updated invitation: Security review', 'Aktualisierte Einladung: Security Review'], preview: ['The meeting time changed...', 'Die Meetingzeit wurde geändert...'],
    isPhishing: false, damage: 80, lossType: ['', ''],
    body: [['The organizer updated the meeting time for Security review.', 'Der Organisator hat die Zeit für Security Review geändert.'], ['Open your calendar to see the latest agenda and attendees.', 'Öffne deinen Kalender, um Agenda und Teilnehmende zu sehen.']],
    cta: { text: ['Open calendar', 'Kalender öffnen'], url: 'https://calendar.google.com/calendar' },
    explain: ['This is a routine calendar update from a real Google domain. It does not request payment, passwords, or secrecy.', 'Das ist eine normale Kalenderänderung von einer echten Google-Domain. Sie fordert keine Zahlung, Passwörter oder Geheimhaltung.'],
    clues: [['Real google.com sender', 'Echter google.com-Absender'], ['Destination is calendar.google.com', 'Ziel ist calendar.google.com'], ['Routine meeting change', 'Normale Terminänderung'], ['No risky action requested', 'Keine riskante Aktion gefordert']],
  },
  {
    category: ['Cloud storage', 'Cloud-Speicher'], difficulty: ['Medium', 'Mittel'], time: ['1:37 PM', '13:37 Uhr'],
    fromName: ['Dropbox Transfer', 'Dropbox Transfer'], fromAddr: 'no-reply@dropboxmail.com',
    subject: ['Files from external audit partner', 'Dateien vom externen Audit-Partner'], preview: ['Your transfer is ready...', 'Deine Übertragung ist bereit...'],
    isPhishing: false, damage: 140, lossType: ['', ''],
    body: [['An external partner sent files through Dropbox Transfer.', 'Ein externer Partner hat Dateien per Dropbox Transfer gesendet.'], ['If you were expecting audit material, open Dropbox and review the sender before downloading.', 'Wenn du Auditmaterial erwartest, öffne Dropbox und prüfe den Absender vor dem Download.']],
    cta: { text: ['Open Dropbox Transfer', 'Dropbox Transfer öffnen'], url: 'https://www.dropbox.com/transfer' },
    explain: ['This one is legitimate but still deserves caution. The domains are Dropbox-controlled and the copy encourages review before downloading.', 'Diese Mail ist legitim, verdient aber Vorsicht. Die Domains gehören zu Dropbox und der Text empfiehlt Prüfung vor dem Download.'],
    clues: [['Dropbox-controlled sender domain', 'Von Dropbox kontrollierte Absenderdomain'], ['HTTPS Dropbox destination', 'HTTPS-Ziel bei Dropbox'], ['No password requested in the email', 'Kein Passwort in der E-Mail verlangt'], ['Download only if the transfer is expected', 'Nur herunterladen, wenn die Übergabe erwartet wird']],
  },
  {
    category: ['Attachment', 'Anhang'], difficulty: ['Medium', 'Mittel'], time: ['2:02 PM', '14:02 Uhr'],
    fromName: ['Scanner MFP-03', 'Scanner MFP-03'], fromAddr: 'scan@mfp-printer.localmail.net',
    subject: ['Scanned document from MFP-03', 'Gescanntes Dokument von MFP-03'], preview: ['Secure scan is attached...', 'Sicherer Scan ist angehängt...'],
    isPhishing: true, damage: 11000, lossType: ['malware launched from a fake scanner attachment', 'Malware aus einem gefälschten Scanner-Anhang gestartet'],
    body: [['A secure document was scanned for you.', 'Ein sicheres Dokument wurde für dich gescannt.'], ['Open the attachment to decrypt and view the file.', 'Öffne den Anhang, um die Datei zu entschlüsseln und anzusehen.']],
    cta: { text: ['Open scan.zip', 'scan.zip öffnen'], url: 'http://localmail-scanner.net/scan.zip' },
    explain: ['Fake scanner emails are common attachment lures. A ZIP download from an outside domain is not how office scanners should deliver files.', 'Gefälschte Scanner-Mails sind häufige Anhang-Köder. Ein ZIP von einer externen Domain ist keine normale Scanner-Zustellung.'],
    clues: [['Outside sender domain for an internal scanner', 'Externe Domain für internen Scanner'], ['ZIP file instead of a normal PDF', 'ZIP-Datei statt normalem PDF'], ['"Decrypt" language adds mystery', '"Entschlüsseln" erzeugt künstliche Wichtigkeit'], ['Unexpected scans should be confirmed before opening', 'Unerwartete Scans vor dem Öffnen bestätigen']],
  },
  {
    category: ['GitHub', 'GitHub'], difficulty: ['Hard', 'Schwer'], time: ['6:41 PM', '18:41 Uhr'],
    fromName: ['GitHub Security', 'GitHub Security'], fromAddr: 'noreply@github.com',
    subject: ['Security alert: deploy key added', 'Sicherheitswarnung: Deploy Key hinzugefügt'], preview: ['A deploy key was added to a repository...', 'Ein Deploy Key wurde zu einem Repository hinzugefügt...'],
    isPhishing: false, damage: 170, lossType: ['', ''],
    body: [['A deploy key was added to a repository you administer.', 'Ein Deploy Key wurde zu einem Repository hinzugefügt, das du administrierst.'], ['If you do not recognize this change, review repository settings in GitHub.', 'Wenn du diese Änderung nicht kennst, prüfe die Repository-Einstellungen in GitHub.']],
    cta: { text: ['Review repository settings', 'Repository-Einstellungen prüfen'], url: 'https://github.com/settings/keys' },
    explain: ['This is a legitimate security notification. It uses the real GitHub domain and asks you to review settings, not enter secrets.', 'Das ist eine legitime Sicherheitsbenachrichtigung. Sie nutzt die echte GitHub-Domain und fordert Prüfung, keine Geheimnisse.'],
    clues: [['Sender is github.com', 'Absender ist github.com'], ['Link stays on github.com', 'Link bleibt auf github.com'], ['Security alert matches admin responsibility', 'Sicherheitswarnung passt zur Admin-Rolle'], ['No attachment or password form', 'Kein Anhang und kein Passwortformular']],
  },
  {
    category: ['GitHub', 'GitHub'], difficulty: ['Hard', 'Schwer'], time: ['6:44 PM', '18:44 Uhr'],
    fromName: ['GitHub Security', 'GitHub Security'], fromAddr: 'noreply@github-security-alerts.com',
    subject: ['Critical token exposure in private repo', 'Kritisches Token-Leak in privatem Repo'], preview: ['Rotate token immediately...', 'Token sofort rotieren...'],
    isPhishing: true, damage: 22000, lossType: ['developer token harvested by a fake GitHub login', 'Entwickler-Token über falsche GitHub-Anmeldung abgegriffen'],
    body: [['We detected a token exposure in a private repository.', 'Wir haben ein Token-Leak in einem privaten Repository erkannt.'], ['Rotate the token immediately to avoid repository suspension.', 'Rotiere das Token sofort, um eine Repository-Sperrung zu vermeiden.']],
    cta: { text: ['Rotate exposed token', 'Geleaktes Token rotieren'], url: 'http://github-security-alerts.com/session' },
    explain: ['The topic is believable, but the domain is not GitHub. Attackers use developer urgency because repo access is valuable.', 'Das Thema ist glaubwürdig, aber die Domain gehört nicht zu GitHub. Angreifer nutzen Entwicklerdruck, weil Repo-Zugriff wertvoll ist.'],
    clues: [['github-security-alerts.com is not github.com', 'github-security-alerts.com ist nicht github.com'], ['Threatens suspension to rush action', 'Drohung mit Sperrung erzeugt Druck'], ['Token handling should happen inside GitHub directly', 'Token-Verwaltung direkt in GitHub durchführen'], ['Private repo wording increases relevance pressure', 'Private-Repos-Formulierung erhöht Relevanzdruck']],
  },
  {
    category: ['Slack', 'Slack'], difficulty: ['Medium', 'Mittel'], time: ['8:19 AM', '8:19 Uhr'],
    fromName: ['Slack', 'Slack'], fromAddr: 'feedback@slack.com',
    subject: ['Your weekly Slack recap is ready', 'Dein wöchentlicher Slack-Rückblick ist bereit'], preview: ['See channels and mentions from last week...', 'Kanäle und Erwähnungen der letzten Woche ansehen...'],
    isPhishing: false, damage: 90, lossType: ['', ''],
    body: [['Your weekly recap is ready.', 'Dein wöchentlicher Rückblick ist bereit.'], ['Open Slack to see your unread mentions and channel highlights.', 'Öffne Slack, um ungelesene Erwähnungen und Channel-Highlights zu sehen.']],
    cta: { text: ['Open Slack', 'Slack öffnen'], url: 'https://slack.com/signin' },
    explain: ['This is a normal Slack notification from slack.com. It is generic, but the sender and destination are legitimate.', 'Das ist eine normale Slack-Benachrichtigung von slack.com. Sie ist generisch, aber Absender und Ziel sind legitim.'],
    clues: [['Sender is slack.com', 'Absender ist slack.com'], ['Destination is slack.com over HTTPS', 'Ziel ist slack.com über HTTPS'], ['No threat or urgent deadline', 'Keine Drohung oder dringende Frist'], ['Can be verified by opening Slack directly', 'Direkt in Slack prüfbar']],
  },
  {
    category: ['Slack', 'Slack'], difficulty: ['Medium', 'Mittel'], time: ['8:26 AM', '8:26 Uhr'],
    fromName: ['Slack Admin', 'Slack Admin'], fromAddr: 'admin@slack-workspace-review.com',
    subject: ['Workspace deactivation scheduled', 'Workspace-Deaktivierung geplant'], preview: ['Confirm active users today...', 'Aktive Nutzer heute bestätigen...'],
    isPhishing: true, damage: 10500, lossType: ['Slack credentials and session tokens stolen', 'Slack-Zugangsdaten und Session-Tokens gestohlen'],
    body: [['Your workspace is scheduled for deactivation due to inactive billing users.', 'Euer Workspace ist wegen inaktiver Billing-Nutzer zur Deaktivierung vorgesehen.'], ['Confirm active users today to keep access.', 'Bestätige heute aktive Nutzer, um den Zugriff zu behalten.']],
    cta: { text: ['Confirm workspace users', 'Workspace-Nutzer bestätigen'], url: 'http://slack-workspace-review.com/confirm' },
    explain: ['This uses a fake Slack admin domain and a deactivation threat. Real workspace administration should be checked inside Slack or the admin console.', 'Das nutzt eine falsche Slack-Admin-Domain und eine Deaktivierungsdrohung. Workspace-Verwaltung gehört in Slack oder die Admin-Konsole.'],
    clues: [['Fake Slack-like domain', 'Falsche Slack-ähnliche Domain'], ['Threatens deactivation', 'Droht mit Deaktivierung'], ['Asks for admin action through email link', 'Fordert Admin-Aktion per E-Mail-Link'], ['Billing/user issues should be checked in Slack directly', 'Billing-/Nutzerfragen direkt in Slack prüfen']],
  },
  {
    category: ['DocuSign', 'DocuSign'], difficulty: ['Easy', 'Einfach'], time: ['11:15 AM', '11:15 Uhr'],
    fromName: ['DocuSign', 'DocuSign'], fromAddr: 'dse@docusign.net',
    subject: ['Completed: NDA countersigned', 'Abgeschlossen: NDA gegengezeichnet'], preview: ['All parties have completed the envelope...', 'Alle Parteien haben den Umschlag abgeschlossen...'],
    isPhishing: false, damage: 120, lossType: ['', ''],
    body: [['All parties have completed the NDA envelope.', 'Alle Parteien haben den NDA-Umschlag abgeschlossen.'], ['You can view the completed document in DocuSign.', 'Du kannst das abgeschlossene Dokument in DocuSign ansehen.']],
    cta: { text: ['View completed document', 'Abgeschlossenes Dokument ansehen'], url: 'https://www.docusign.com/' },
    explain: ['This is a legitimate DocuSign completion notice. The sender pattern and destination are consistent with DocuSign.', 'Das ist eine legitime DocuSign-Abschlussmail. Absender und Ziel passen zu DocuSign.'],
    clues: [['docusign.net is used for DocuSign envelope mail', 'docusign.net wird für DocuSign-Umschläge genutzt'], ['HTTPS DocuSign destination', 'HTTPS-Ziel bei DocuSign'], ['No surprise payment or password ask', 'Keine überraschende Zahlung oder Passwortforderung'], ['Completion notice matches a normal signing flow', 'Abschlussmail passt zu normalem Signaturablauf']],
  },
  {
    category: ['DocuSign', 'DocuSign'], difficulty: ['Medium', 'Mittel'], time: ['11:18 AM', '11:18 Uhr'],
    fromName: ['DocuSign', 'DocuSign'], fromAddr: 'signature@docusign-securefiles.com',
    subject: ['Urgent signature required: payment authorization', 'Dringende Signatur nötig: Zahlungsfreigabe'], preview: ['Finance is waiting for approval...', 'Finance wartet auf Freigabe...'],
    isPhishing: true, damage: 31000, lossType: ['payment authorization approved on a fake signing workflow', 'Zahlungsfreigabe in einem gefälschten Signaturprozess bestätigt'],
    body: [['A payment authorization is waiting for signature.', 'Eine Zahlungsfreigabe wartet auf Signatur.'], ['Finance marked this as urgent for today.', 'Finance hat dies für heute als dringend markiert.']],
    cta: { text: ['Review and sign', 'Prüfen und signieren'], url: 'http://docusign-securefiles.com/envelope' },
    explain: ['The domain is not DocuSign, and the document topic is high-risk. Payment approvals need process verification.', 'Die Domain gehört nicht zu DocuSign und das Dokumentthema ist riskant. Zahlungsfreigaben brauchen Prozessprüfung.'],
    clues: [['docusign-securefiles.com is fake', 'docusign-securefiles.com ist falsch'], ['Urgent payment authorization is high-risk', 'Dringende Zahlungsfreigabe ist Hochrisiko'], ['Pressure comes from "Finance"', 'Druck kommt angeblich von Finance'], ['Open DocuSign independently if unsure', 'DocuSign bei Zweifel unabhängig öffnen']],
  },
  {
    category: ['Travel', 'Reise'], difficulty: ['Medium', 'Mittel'], time: ['7:52 PM', '19:52 Uhr'],
    fromName: ['Travel Desk', 'Travel Desk'], fromAddr: 'travel@northwind-tools.com',
    subject: ['Hotel booking policy update', 'Update zur Hotelbuchungsrichtlinie'], preview: ['New nightly cap starts next month...', 'Neue Nachtgrenze gilt ab nächstem Monat...'],
    isPhishing: false, damage: 100, lossType: ['', ''],
    body: [['The hotel nightly cap changes next month for domestic travel.', 'Die Hotel-Nachtgrenze ändert sich nächsten Monat für Inlandsreisen.'], ['No action is needed for existing bookings. Use the travel portal for new trips.', 'Für bestehende Buchungen ist nichts zu tun. Nutze das Reiseportal für neue Reisen.']],
    explain: ['This is a normal internal policy notice. It asks for no credentials, payment, or immediate action.', 'Das ist eine normale interne Richtlinienmail. Sie fordert keine Zugangsdaten, Zahlung oder Sofortaktion.'],
    clues: [['Internal sender domain', 'Interne Absenderdomain'], ['No link needed to act', 'Kein Link für Handlung nötig'], ['No urgent threat', 'Keine dringende Drohung'], ['Specific policy detail can be checked internally', 'Konkrete Richtlinie intern prüfbar']],
  },
  {
    category: ['Travel', 'Reise'], difficulty: ['Medium', 'Mittel'], time: ['7:58 PM', '19:58 Uhr'],
    fromName: ['Travel Desk', 'Travel Desk'], fromAddr: 'travel@northwind-traveldesk.com',
    subject: ['Action required: rebook cancelled hotel', 'Handlung nötig: storniertes Hotel neu buchen'], preview: ['Card verification required tonight...', 'Kartenprüfung heute Abend nötig...'],
    isPhishing: true, damage: 1800, lossType: ['corporate card details captured on a fake travel page', 'Firmenkartendaten auf falscher Reiseseite abgegriffen'],
    body: [['Your hotel booking for next week was cancelled by the property.', 'Deine Hotelbuchung für nächste Woche wurde vom Hotel storniert.'], ['Verify the company card tonight so we can rebook before rates increase.', 'Bestätige die Firmenkarte heute Abend, damit wir vor Preiserhöhung neu buchen können.']],
    cta: { text: ['Verify company card', 'Firmenkarte bestätigen'], url: 'http://northwind-traveldesk.com/card' },
    explain: ['The travel context is plausible, but the domain is outside the company and asks for card verification under deadline pressure.', 'Der Reisekontext ist plausibel, aber die Domain ist extern und verlangt Kartenprüfung unter Zeitdruck.'],
    clues: [['External look-alike travel domain', 'Externe Look-alike-Reisedomain'], ['Requests company card details', 'Fordert Firmenkartendaten'], ['Evening deadline creates pressure', 'Abendfrist erzeugt Druck'], ['Travel changes should be handled in the known portal', 'Reiseänderungen im bekannten Portal bearbeiten']],
  },
  {
    category: ['Survey', 'Umfrage'], difficulty: ['Easy', 'Einfach'], time: ['12:45 PM', '12:45 Uhr'],
    fromName: ['People Team', 'People Team'], fromAddr: 'people@northwind-tools.com',
    subject: ['Anonymous pulse survey opens today', 'Anonyme Pulse-Umfrage startet heute'], preview: ['Five questions, open until Friday...', 'Fünf Fragen, offen bis Freitag...'],
    isPhishing: false, damage: 80, lossType: ['', ''],
    body: [['Our anonymous pulse survey is open until Friday.', 'Unsere anonyme Pulse-Umfrage ist bis Freitag geöffnet.'], ['You can answer five questions from the intranet survey tile.', 'Du kannst fünf Fragen über die Umfrage-Kachel im Intranet beantworten.']],
    explain: ['This is a safe internal survey announcement. It points to the intranet and avoids collecting credentials through email.', 'Das ist eine sichere interne Umfrageankündigung. Sie verweist aufs Intranet und sammelt keine Zugangsdaten per E-Mail.'],
    clues: [['Internal People sender', 'Interner People-Absender'], ['No external survey link', 'Kein externer Umfragelink'], ['No reward or threat', 'Keine Belohnung oder Drohung'], ['Uses the normal intranet path', 'Nutzt den normalen Intranet-Weg']],
  },
  {
    category: ['Survey', 'Umfrage'], difficulty: ['Easy', 'Einfach'], time: ['12:51 PM', '12:51 Uhr'],
    fromName: ['Employee Rewards', 'Employee Rewards'], fromAddr: 'rewards@survey-prizehub.com',
    subject: ['You were selected for a EUR 75 voucher', 'Du wurdest für einen 75-EUR-Gutschein ausgewählt'], preview: ['Complete the employee survey...', 'Mitarbeiterumfrage abschließen...'],
    isPhishing: true, damage: 760, lossType: ['personal data and card verification captured by a fake reward survey', 'Personendaten und Kartenprüfung durch Fake-Belohnungsumfrage abgegriffen'],
    body: [['You were selected for an employee reward voucher.', 'Du wurdest für einen Mitarbeiter-Gutschein ausgewählt.'], ['Complete the short survey and verify delivery details today.', 'Fülle die kurze Umfrage aus und bestätige heute die Lieferdaten.']],
    cta: { text: ['Claim voucher', 'Gutschein sichern'], url: 'http://survey-prizehub.com/northwind' },
    explain: ['Prize lures trade on curiosity and reward. The external domain and "verify delivery" request are the warning signs.', 'Gewinnköder nutzen Neugier und Belohnung. Externe Domain und "Lieferdaten bestätigen" sind Warnzeichen.'],
    clues: [['External prize domain', 'Externe Gewinn-Domain'], ['Unexpected voucher reward', 'Unerwarteter Gutschein'], ['Personal details requested', 'Personendaten werden abgefragt'], ['Reward urgency lowers skepticism', 'Belohnungsdruck senkt Skepsis']],
  },
  {
    category: ['Zoom', 'Zoom'], difficulty: ['Medium', 'Mittel'], time: ['9:50 AM', '9:50 Uhr'],
    fromName: ['Zoom', 'Zoom'], fromAddr: 'no-reply@zoom.us',
    subject: ['Cloud recording is now available', 'Cloud-Aufzeichnung ist verfügbar'], preview: ['Your meeting recording is ready...', 'Deine Meeting-Aufzeichnung ist bereit...'],
    isPhishing: false, damage: 90, lossType: ['', ''],
    body: [['Your cloud recording is now available.', 'Deine Cloud-Aufzeichnung ist verfügbar.'], ['Open Zoom to view, share, or delete the recording.', 'Öffne Zoom, um die Aufzeichnung anzusehen, zu teilen oder zu löschen.']],
    cta: { text: ['Open Zoom recordings', 'Zoom-Aufzeichnungen öffnen'], url: 'https://zoom.us/recording' },
    explain: ['This is a legitimate Zoom notification. It uses zoom.us and contains no urgent credential demand.', 'Das ist eine legitime Zoom-Benachrichtigung. Sie nutzt zoom.us und fordert keine dringende Anmeldung.'],
    clues: [['Sender is zoom.us', 'Absender ist zoom.us'], ['Link points to zoom.us', 'Link zeigt auf zoom.us'], ['Normal meeting-recording workflow', 'Normaler Meeting-Aufzeichnungsablauf'], ['No threat or invoice', 'Keine Drohung oder Rechnung']],
  },
  {
    category: ['Zoom', 'Zoom'], difficulty: ['Medium', 'Mittel'], time: ['9:57 AM', '9:57 Uhr'],
    fromName: ['Zoom Cloud', 'Zoom Cloud'], fromAddr: 'recordings@zoom-cloudfiles.com',
    subject: ['Recording will be deleted in 2 hours', 'Aufzeichnung wird in 2 Stunden gelöscht'], preview: ['Download before deletion...', 'Vor Löschung herunterladen...'],
    isPhishing: true, damage: 4700, lossType: ['credentials stolen through a fake recording download page', 'Zugangsdaten über falsche Recording-Downloadseite gestohlen'],
    body: [['Your meeting recording exceeded the free storage limit.', 'Deine Meeting-Aufzeichnung überschreitet das freie Speicherlimit.'], ['Download it within 2 hours before permanent deletion.', 'Lade sie innerhalb von 2 Stunden herunter, bevor sie endgültig gelöscht wird.']],
    cta: { text: ['Download recording', 'Aufzeichnung herunterladen'], url: 'http://zoom-cloudfiles.com/recording' },
    explain: ['The recording story is plausible, but the domain is not Zoom and the deletion timer creates pressure.', 'Die Recording-Geschichte ist plausibel, aber die Domain ist nicht Zoom und der Lösch-Timer erzeugt Druck.'],
    clues: [['Fake Zoom-like domain', 'Falsche Zoom-ähnliche Domain'], ['Two-hour deletion pressure', 'Zwei-Stunden-Löschdruck'], ['Download link leads outside Zoom', 'Download-Link führt außerhalb von Zoom'], ['Open Zoom directly to verify recordings', 'Zoom direkt öffnen und Aufzeichnungen prüfen']],
  },
  {
    category: ['Tax', 'Steuer'], difficulty: ['Hard', 'Schwer'], time: ['6:33 AM', '6:33 Uhr'],
    fromName: ['Bundeszentralamt', 'Bundeszentralamt'], fromAddr: 'service@bzst-rueckerstattung.de',
    subject: ['Tax refund ready for confirmation', 'Steuerrückerstattung zur Bestätigung bereit'], preview: ['Confirm IBAN for refund...', 'IBAN für Rückerstattung bestätigen...'],
    isPhishing: true, damage: 2100, lossType: ['bank and identity details harvested on a fake tax refund page', 'Bank- und Identitätsdaten auf falscher Steuerseite abgegriffen'],
    body: [['A tax refund of EUR 312.18 is ready for payout.', 'Eine Steuerrückerstattung über 312,18 EUR ist zur Auszahlung bereit.'], ['Confirm your IBAN and identity details within 48 hours.', 'Bestätige IBAN und Identitätsdaten innerhalb von 48 Stunden.']],
    cta: { text: ['Confirm refund details', 'Rückerstattung bestätigen'], url: 'http://bzst-rueckerstattung.de/portal' },
    explain: ['Refund lures ask for bank and identity data. The domain is not a trustworthy government domain and the deadline is pressure.', 'Rückerstattungsköder fragen Bank- und Identitätsdaten ab. Die Domain ist keine vertrauenswürdige Behörden-Domain und die Frist erzeugt Druck.'],
    clues: [['Government-like but unofficial domain', 'Behördenähnliche, aber falsche Domain'], ['Asks for IBAN and identity data', 'Fragt IBAN und Identitätsdaten ab'], ['Refund reward reduces skepticism', 'Rückerstattung senkt Skepsis'], ['Use official portals manually', 'Offizielle Portale manuell öffnen']],
  },
  {
    category: ['Banking', 'Banking'], difficulty: ['Easy', 'Einfach'], time: ['10:04 AM', '10:04 Uhr'],
    fromName: ['N26', 'N26'], fromAddr: 'no-reply@n26.com',
    subject: ['Card payment declined', 'Kartenzahlung abgelehnt'], preview: ['A payment was declined due to limits...', 'Eine Zahlung wurde wegen Limits abgelehnt...'],
    isPhishing: false, damage: 120, lossType: ['', ''],
    body: [['A recent card payment was declined because it exceeded your current limit.', 'Eine Kartenzahlung wurde abgelehnt, weil sie dein aktuelles Limit überschritten hat.'], ['Open the app to review card controls. We will never ask for your PIN by email.', 'Öffne die App, um Kartenlimits zu prüfen. Wir fragen deine PIN nie per E-Mail ab.']],
    explain: ['This is a safe banking notice because it tells you to use the app and explicitly avoids collecting secrets.', 'Das ist eine sichere Bankbenachrichtigung, weil sie auf die App verweist und keine Geheimnisse abfragt.'],
    clues: [['Sender is the real bank domain', 'Absender ist die echte Bankdomain'], ['No email login link', 'Kein Login-Link in der E-Mail'], ['Tells you to use the app', 'Verweist auf die App'], ['States that PIN is never requested', 'Sagt klar, dass keine PIN abgefragt wird']],
  },
  {
    category: ['Atlassian', 'Atlassian'], difficulty: ['Hard', 'Schwer'], time: ['2:29 PM', '14:29 Uhr'],
    fromName: ['Atlassian Access', 'Atlassian Access'], fromAddr: 'access@atlassian-security.net',
    subject: ['SSO policy mismatch detected', 'SSO-Richtlinienkonflikt erkannt'], preview: ['Re-authenticate workspace admins...', 'Workspace-Admins erneut authentifizieren...'],
    isPhishing: true, damage: 15000, lossType: ['admin credentials stolen from a fake Atlassian SSO page', 'Admin-Zugangsdaten über falsche Atlassian-SSO-Seite gestohlen'],
    body: [['We detected a mismatch between your SSO policy and active users.', 'Wir haben einen Konflikt zwischen SSO-Richtlinie und aktiven Nutzern erkannt.'], ['Workspace admins must re-authenticate today to avoid access disruption.', 'Workspace-Admins müssen sich heute erneut authentifizieren, um Störungen zu vermeiden.']],
    cta: { text: ['Re-authenticate admins', 'Admins erneut authentifizieren'], url: 'http://atlassian-security.net/sso' },
    explain: ['This targets admins with realistic SSO language. The domain is not Atlassian and the action should happen in the real admin portal.', 'Das zielt mit realistischer SSO-Sprache auf Admins. Die Domain ist nicht Atlassian und die Aktion gehört ins echte Admin-Portal.'],
    clues: [['Fake Atlassian security domain', 'Falsche Atlassian-Security-Domain'], ['Admin-targeted urgency', 'Admin-Zeitdruck'], ['SSO changes are high impact', 'SSO-Änderungen haben hohe Wirkung'], ['Use the known admin URL directly', 'Bekannte Admin-URL direkt nutzen']],
  },
  {
    category: ['Atlassian', 'Atlassian'], difficulty: ['Medium', 'Mittel'], time: ['2:36 PM', '14:36 Uhr'],
    fromName: ['Jira', 'Jira'], fromAddr: 'jira@atlassian.com',
    subject: ['Issue assigned to you: SEC-184', 'Vorgang zugewiesen: SEC-184'], preview: ['A Jira issue was assigned to you...', 'Ein Jira-Vorgang wurde dir zugewiesen...'],
    isPhishing: false, damage: 100, lossType: ['', ''],
    body: [['A Jira issue was assigned to you by the security board.', 'Ein Jira-Vorgang wurde dir vom Security-Board zugewiesen.'], ['Open Jira to review the issue and comments.', 'Öffne Jira, um Vorgang und Kommentare zu prüfen.']],
    cta: { text: ['Open Jira', 'Jira öffnen'], url: 'https://www.atlassian.com/software/jira' },
    explain: ['This is a normal Jira notification from Atlassian. It points to a real Atlassian destination and asks for routine review.', 'Das ist eine normale Jira-Benachrichtigung von Atlassian. Sie verweist auf ein echtes Atlassian-Ziel und fordert normale Prüfung.'],
    clues: [['Sender is atlassian.com', 'Absender ist atlassian.com'], ['Routine ticket assignment', 'Normale Ticket-Zuweisung'], ['No attachment or money request', 'Kein Anhang oder Geldwunsch'], ['Can be verified in Jira directly', 'Direkt in Jira prüfbar']],
  },
];

function localize(seed: ScenarioSeed, localeIndex: 0 | 1): LabEmail {
  return {
    channel: seed.channel,
    category: seed.category[localeIndex],
    difficulty: seed.difficulty[localeIndex],
    time: seed.time[localeIndex],
    fromName: seed.fromName[localeIndex],
    fromAddr: seed.fromAddr,
    subject: seed.subject[localeIndex],
    preview: seed.preview[localeIndex],
    isPhishing: seed.isPhishing,
    damage: seed.damage,
    lossType: seed.lossType[localeIndex],
    body: [
      { type: 'text', text: seed.body[0][localeIndex] },
      { type: 'text', text: seed.body[1][localeIndex] },
      ...(seed.body[2] ? [{ type: 'text' as const, text: seed.body[2][localeIndex] }] : []),
      ...(seed.cta ? [{ type: 'cta' as const, text: seed.cta.text[localeIndex], url: seed.cta.url }] : []),
    ],
    explain: seed.explain[localeIndex],
    clues: seed.clues.map(clue => clue[localeIndex]),
  };
}

export const extraLabEmails: Record<string, LabEmail[]> = {
  en: seeds.map(seed => localize(seed, 0)),
  de: seeds.map(seed => localize(seed, 1)),
};
