import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Breadcrumbs from "@/components/common/Breadcrumbs";
import { getPublication, publications } from "@/data/publications";
import { buildMetadata, SITE_NAME, SITE_URL } from "@/i18n/metadata";
import { Link } from "@/i18n/navigation";

export function generateStaticParams() { return publications.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale, slug } = await params; const item = getPublication(slug); if (!item) return {}; const p = item.content[locale === "de" ? "de" : "en"]; return buildMetadata({ locale, title: `${p.title} | niwo`, description: p.summary, path: `/insights/${slug}`, ogType: "article", articleDates: { published: item.published, modified: item.updated }, socialImageAlt: p.title }); }
function Section({ id, title, items }: { id: string; title: string; items: string[] }) { return <section id={id} className="scroll-mt-28 border-t border-white/[0.08] pt-10"><h2 className="font-mono text-2xl font-semibold text-white">{title}</h2><ul className="mt-5 space-y-3">{items.map((x) => <li key={x} className="flex gap-3 leading-7 text-zinc-300"><span aria-hidden="true" className="text-[var(--color-accent-light)]">&rarr;</span>{x}</li>)}</ul></section>; }
export default async function PublicationPage({ params }: { params: Promise<{ locale: string; slug: string }> }) { const { locale, slug } = await params; const item = getPublication(slug); if (!item) notFound(); const lang = locale === "de" ? "de" : "en"; const p = item.content[lang]; const l = lang === "de" ? { home: "Start", insights: "Beiträge", summary: "Zusammenfassung", context: "Kontext", method: "Methode", evidence: "Nachweise", findings: "Befunde", limitations: "Grenzen", implications: "Praktische Bedeutung", references: "Quellen", related: "Verwandte Inhalte", author: "Autor", reviewed: "Geprüft", updated: "Aktualisiert" } : { home: "Home", insights: "Insights", summary: "Summary", context: "Context", method: "Method", evidence: "Evidence", findings: "Findings", limitations: "Limitations", implications: "Practical implications", references: "References", related: "Related content", author: "Author", reviewed: "Reviewed", updated: "Updated" }; const url = `${SITE_URL}/${locale}/insights/${slug}`; const articleJsonLd = { "@context": "https://schema.org", "@type": "Article", headline: p.title, description: p.summary, author: { "@type": "Person", name: item.author }, publisher: { "@type": "Organization", name: SITE_NAME, url: SITE_URL }, datePublished: item.published, dateModified: item.updated, inLanguage: locale, mainEntityOfPage: url };
  return <article className="bg-[var(--background)] px-6 pb-28 pt-28 sm:px-10 lg:px-16"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }} /><div className="mx-auto max-w-4xl"><Breadcrumbs locale={locale} items={[{ label: l.home, href: "" }, { label: l.insights, href: "/insights" }, { label: p.title, href: `/insights/${slug}` }]} /><header className="mt-10 border-y border-white/[0.08] py-12"><p className="font-mono text-xs uppercase tracking-[0.24em] text-[var(--color-accent-light)]">{item.type.replaceAll("-", " ")}{item.sanitized ? ` · ${lang === "de" ? "bereinigt" : "sanitized"}` : ""}</p><h1 className="mt-5 font-mono text-4xl font-bold leading-tight text-white sm:text-5xl">{p.title}</h1><p className="mt-7 text-lg leading-9 text-zinc-200">{p.summary}</p><dl className="mt-7 flex flex-wrap gap-x-8 gap-y-3 font-mono text-xs text-zinc-500"><div><dt className="inline text-zinc-300">{l.author}: </dt><dd className="inline">{item.author}</dd></div><div><dt className="inline text-zinc-300">{l.reviewed}: </dt><dd className="inline"><time dateTime={item.reviewed}>{item.reviewed}</time></dd></div><div><dt className="inline text-zinc-300">{l.updated}: </dt><dd className="inline"><time dateTime={item.updated}>{item.updated}</time></dd></div></dl></header><div className="mt-14 space-y-14"><section><h2 className="font-mono text-2xl font-semibold text-white">{l.context}</h2><p className="mt-5 leading-8 text-zinc-300">{p.context}</p></section><Section id="method" title={l.method} items={p.method} /><Section id="evidence" title={l.evidence} items={p.evidence} /><Section id="findings" title={l.findings} items={p.findings} /><Section id="limitations" title={l.limitations} items={p.limitations} /><Section id="implications" title={l.implications} items={p.implications} /><section id="references" className="border-t border-white/[0.08] pt-10"><h2 className="font-mono text-2xl font-semibold text-white">{l.references}</h2><ul className="mt-5 space-y-4">{p.references.map((ref) => <li key={ref.href}><a href={ref.href} target="_blank" rel="noopener noreferrer" className="text-[var(--color-accent-light)] hover:text-white">{ref.label} — {ref.organization}<span className="sr-only"> ({lang === "de" ? "öffnet in neuem Tab" : "opens in a new tab"})</span></a></li>)}</ul></section><section className="border-t border-white/[0.08] pt-10"><h2 className="font-mono text-2xl font-semibold text-white">{l.related}</h2><div className="mt-5 flex flex-wrap gap-5">{item.relatedServices.map((x) => <Link key={x} href={`/services/${x}`} className="font-mono text-sm text-[var(--color-accent-light)] hover:text-white">{x.replaceAll("-", " ")} &rarr;</Link>)}{item.relatedTopics.map((x) => <Link key={x} href={`/topics/${x}`} className="font-mono text-sm text-[var(--color-accent-light)] hover:text-white">{x.replaceAll("-", " ")} &rarr;</Link>)}</div></section></div></div></article>;
}
